version: "3"

services:

  mongodb:
    image: mongo:latest
    hostname: mongodb
    restart: "always"
    networks:
      - atlant
    volumes:
      - mongodb:${MONGODB_DATA}
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}

  proxy:
    build:
      context: .
      dockerfile: envoy.Dockerfile
    restart: "always"
    networks:
      - atlant
    depends_on:
      - app1
      - app2
    ports:
      - ${PROXY_PORT}:${PROXY_PORT}

  app1:
    build:
      context: .
      dockerfile: server.Dockerfile
      args:
        VERSION: ${VERSION}
    image: ${SERVICE_NAME}
    hostname: ${SERVICE_NAME}
    restart: "always"
    networks:
      - atlant
    depends_on:
      - mongodb
    environment:
      HOST: 0.0.0.0
      PORT: ${SERVICE_PORT}
      MONGO_URI: mongodb://mongodb:${MONGODB_PORT}
      LOG_LEVEL: ${LOG_LEVEL}

  app2:
    build:
      context: .
      dockerfile: server.Dockerfile
      args:
        VERSION: ${VERSION}
    image: ${SERVICE_NAME}
    hostname: ${SERVICE_NAME}
    restart: "always"
    networks:
      - atlant
    depends_on:
      - mongodb
    environment:
      HOST: 0.0.0.0
      PORT: ${SERVICE_PORT}
      MONGO_URI: mongodb://mongodb:${MONGODB_PORT}
      LOG_LEVEL: ${LOG_LEVEL}

networks:
  atlant:
    driver: bridge

volumes:
  mongodb:
